---
- name: Install httpd package
  yum:
        name: httpd
        state: present

- name: start http
  service:
        name: httpd
        state: started

- name: Open port for http 
  firewalld:
        service: http
        permanent: true
        state: enabled

- name: Restart firewalld
  service:
        name: firewalld
        state: reloaded


